# Generated by Django 4.2.6 on 2023-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=10)),
                ('date_of_creating', models.CharField(max_length=10)),
            ],
        ),
    ]
