# Generated by Django 4.2.6 on 2023-11-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='href',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.CharField(default='-', max_length=600),
        ),
    ]
