# Generated by Django 4.2.6 on 2023-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_card_href_card_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img_path',
            field=models.CharField(default='-', max_length=40),
        ),
    ]
