# Generated by Django 4.2.6 on 2023-11-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_card_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='history_period',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
